### ISSUE TITLE
Python 3.12 CLI relocate : 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by mattthhh** [kevinconway/venvctrl#30]
Hi there, when I try to run this command on Python 3.12 : `python -m venvctrl.cli.relocate --source=source_dir --destination=dest_dir`, I get this traceback :
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "python3.12/site-packages/venvctrl/cli/relocate.py", line 57, in <module>
    main()
  File "python3.12/site-packages/venvctrl/cli/relocate.py", line 52, in main
    relocate(args.source, args.destination, args.move)
  File "python3.12/site-packages/venvctrl/cli/relocate.py", line 24, in relocate
    venv.relocate(destination)
  File "python3.12/site-packages/venvctrl/venv/relocate.py", line 28, in relocate
     activate.vpath = destination
     ^^^^^^^^^
  File "python3.12/site-packages/venvctrl/venv/base.py", line 240, in vpath
    new_line = old_line.replace(old_vpath, new_vpath)
                      ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```
It seems to appear only in Python3.12, I try the same build in Python3.9 and Python3.11 and it works without any problems. Any ideas ?

**Comment by mattthhh** [comment]
I think I found the problem, it is in `venvctrl/venv/base.py` class `ActivateFile`. The `_find_vpath` try to search for a line with the variable `VIRTUAL_ENV` set in `venv/bin/activate`, but this line isn't present for this file when creating a venv in Python 3.12

**Comment by kevinconway** [comment]
Ah, you're using the standard library `venv` rather than the external `virtualenv` package and hitting the same issue as https://github.com/kevinconway/venvctrl/issues/28.

I appreciate the PR. It doesn't cover some of the edge cases around `venv` path management in the bash activation script, though. Specifically, the `venv` package has multiple definitions of `VIRTUAL_ENV` throughout the activation script instead of only one location like it used to. I have an existing PR that does cover the edges cases and adds tests for Python 3.12 and using `venv` in addition to `virtualenv` here: https://github.com/kevinconway/venvctrl/pull/29. The only reason I haven't merged it yet is because I forgot about it after not hearing from the other issue reporter in a while. Take a look at the PR and let me know if you see any major issues. If not then I'll merge it and get a new package deployed.

As a historical note, I created this project nearly 10 years ago when there was no standard library `venv` module. The term `venv` back then meant `virtualenv`. The built-in `venv` module that exists now is a derivative of `virtualenv` and has now started to change independently. I'm not certain how much I want to take on maintaining compatibility with both tools but I'm willing to try it out and see what sort of issues come my way in the future.

**Comment by kevinconway** [comment]
You should be good to go. The 0.7.0 version is published to PyPI.
